added Pie, vertical Bar and Composed Charts
omni-srejitk/omniverse pull request #17
Opened 2022-11-21 10:55 UTC by naresh130199

Added graph components

2022-11-22 05:17 UTC, omni-srejitk requested changes
Good work. Left few minor changes. 
Keep the props in mind, and in the arguments section

2022-11-22 05:17 UTC, omni-srejitk commented on dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
> +  // BarChartData for Bar chart component, XAxisValue and YAxisValue
Where do we take in the XAxis Value and YAxis Value? Did we miss that here

2022-11-22 05:17 UTC, omni-srejitk commented on dashboard/src/components/Charts/ComposedChart/ComposedChartComp.jsx
> +        {/* <Area type="monotone" dataKey="" fill="#8884d8" stroke="#8884d8" /> */}
Remove the commented code if not needed

2022-11-22 05:17 UTC, omni-srejitk commented on dashboard/src/components/Charts/PieChart/PieChartComp.jsx
> +        dataKey="value"
We need to take in the dataKey as a prop here too

2022-11-22 05:17 UTC, omni-srejitk commented on dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
> +          dataKey={'XAxisValue'}
Correct this. This should take in the prop that you add rather than the string

2022-11-24 06:57 UTC, naresh130199 commented on dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
> +  // BarChartData for Bar chart component, XAxisValue and YAxisValue
changed that now data props should provide the required data

2022-11-24 07:18 UTC, naresh130199 commented on dashboard/src/components/Charts/ComposedChart/ComposedChartComp.jsx
> +        {/* <Area type="monotone" dataKey="" fill="#8884d8" stroke="#8884d8" /> */}
yep removed it

2022-11-24 07:18 UTC, naresh130199 commented on dashboard/src/components/Charts/PieChart/PieChartComp.jsx
> +        dataKey="value"
done

2022-11-24 07:19 UTC, naresh130199 commented on dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
> +          dataKey={'XAxisValue'}
yeah, now it will be taking in props

2022-11-24 07:24 UTC, merged