FEAT - Analytics code done
omni-srejitk/omniverse pull request #25
Opened 2022-11-22 15:02 UTC by ayusdas2000

2022-11-23 08:21 UTC, omni-srejitk requested changes
A few minor suggestions, have a look into it.

2022-11-23 08:21 UTC, omni-srejitk commented on dashboard/src/utils/helperFunctions.js
> +  const presentDate = moment().format("DD-MM-YY");
Let's calculate the last 30 days along with it here? So that we can filter based upon that  and select based upon that.

2022-11-23 08:21 UTC, omni-srejitk commented on dashboard/src/utils/helperFunctions.js
> +        moment(date, "DD-MM-YY").isBetween(
Can you have a look into your linting rules cause this shouldn't be reflected as a change. Since we're using single ticks everywhere

2022-11-24 06:54 UTC, ayusdas2000 commented on dashboard/src/utils/helperFunctions.js
> +  const presentDate = moment().format("DD-MM-YY");
this is done

2022-11-24 06:54 UTC, ayusdas2000 commented on dashboard/src/utils/helperFunctions.js
> +        moment(date, "DD-MM-YY").isBetween(
this is also done

2022-11-24 07:33 UTC, omni-srejitk approved these changes
Good work!

2022-11-24 07:33 UTC, merged